image: node:latest

stages:
  - restore
  - test
  - build
  #- deploy

cache:
  paths:
  - apt-cache/
  - node_modules/

  restore_dependencies:
  stage: restore
  script:
    # installs node packages
    - npm ci
    # installs chromium for ui tests
    - apt-get dir::cache::archives="apt-cache" install chromium-browser


unit_tests:
  stage: test

  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

test_e2e:
  stage: test
  
  script:
    - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js

build:
  stage: build

  # builds angular project in production mode
  script:
    - npm run build -- --prod

  # defines build artifact
  artifacts:
    paths:
      - dist/OnlineResume/

# deploy:
#   stage: deploy

#   before_script:
#     - apt-get update -qy
#     - apt-get install -y lftp
  
#   script:
#     - lftp -e "open ftp://jamestowers.tech; user $FTP_Username $FTP_Password;
#       mirror -X .* -X .*/ --reverse --verbose --delete local-folder/ destination-folder/; bye"
