image: node:latest

stages:
  - restore
  - test
  - build
  #- deploy

cache:
  paths:
  - apt-cache/
  - node_modules/

restore_dependencies:
  stage: restore
  script:
    # install node packages
    - npm ci
    # synchronize package index files
    - apt-get update
    # enable universe repository
    - apt-get install -y software-properties-common
    - add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
    # synchronize package index files
    - apt-get update
    # install chromium for ui tests
    - apt-get -o dir::cache::archives="apt-cache" install -y chromium-browser


unit_tests:
  stage: test

  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

test_e2e:
  stage: test
  
  script:
    - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js

build:
  stage: build

  # builds angular project in production mode
  script:
    - npm run build -- --prod

  # defines build artifact
  artifacts:
    paths:
      - dist/OnlineResume/

# deploy:
#   stage: deploy

#   before_script:
#     - apt-get update -qy
#     - apt-get install -y lftp
  
#   script:
#     - lftp -e "open ftp://jamestowers.tech; user $FTP_Username $FTP_Password;
#       mirror -X .* -X .*/ --reverse --verbose --delete local-folder/ destination-folder/; bye"
