image: node:latest

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build -- --prod
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    # apt-get install chromium-browser
    npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

# deploy:
#   stage: deploy
