image: node:latest

stages:
  - restore
  - test
  - build
  - deploy

cache:
  paths:
  - node_modules/

restore_dependencies:
  stage: restore
  script:
    # install node packages
    - npm ci

.install_chrome: &install_chrome
  # synchronize package index files
  - apt-get update
  # install libraries required for chrome
  - apt-get install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator3-1 libnss3 lsb-release xdg-utils
  # download chrome package
  - wget -nv https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  # install chrome
  - dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

unit_tests:
  stage: test

  #install chrome for tests
  before_script: *install_chrome

  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

test_e2e:
  stage: test
  
  #install chrome for tests
  before_script: *install_chrome

  script:
    - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js

build:
  stage: build

  # builds angular project in production mode
  script:
    - npm run build -- --prod

  # defines build artifact
  artifacts:
    paths:
      - dist/OnlineResume/

deploy:
  stage: deploy

  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
  
  script:
    - lftp -e "set ssl:verify-certificate no; open ftp://jamestowers.tech; user $FTP_Username $FTP_Password;
      mirror --reverse --verbose --delete dist/ public_html/; bye"
