image: node:latest

stages:
  - restore
  - test
  - build
  #- deploy

cache:
  paths:
  - apt-cache/
  - node_modules/

restore_dependencies:
  stage: restore
  script:
    # install node packages
    - npm ci
    # synchronize package index files
    - apt-get update
    # install libraries required for chrome
    - apt-get -o dir::cache::archives="apt-cache" install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils


unit_tests:
  stage: test

  #install chrome for tests
  before_script:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

test_e2e:
  stage: test
  
  #install chrome for tests
  before_script:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
    
  script:
    - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js

build:
  stage: build

  # builds angular project in production mode
  script:
    - npm run build -- --prod

  # defines build artifact
  artifacts:
    paths:
      - dist/OnlineResume/

# deploy:
#   stage: deploy

#   before_script:
#     - apt-get update -qy
#     - apt-get install -y lftp
  
#   script:
#     - lftp -e "open ftp://jamestowers.tech; user $FTP_Username $FTP_Password;
#       mirror -X .* -X .*/ --reverse --verbose --delete local-folder/ destination-folder/; bye"
